--- #YAML:1.0
name:               Data-Printer
version:            0.21
abstract:           colored pretty-print of Perl data structures and objects
author:
    - Breno G. de Oliveira <garu@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:             0
    Class::MOP:       0.65
    Clone:            0
    Fcntl:            0
    File::HomeDir:    0.91
    File::Spec:       0
    Hash::FieldHash:  0
    Scalar::Util:     0
    Sort::Naturally:  0
    Term::ANSIColor:  3
    Test::More:       0.88
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-Printer
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/garu/Data-Printer
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
